//! `xgram mcp install` + `xgram identity inject` — 사용자 / LLM 의 자율 셋업.
//!
//! 흐름:
//!   - mcp install: `.claude.json` (user scope) 또는 `.mcp.json` (project scope) 에
//!     openxgram 서버 등록. 파일이 없으면 생성. 이미 있으면 갱신.
//!   - identity inject: 현재 프로젝트 폴더의 `CLAUDE.md` 에 OpenXgram identity
//!     context 블록을 주입/갱신. marker 기반 (`<!-- OPENXGRAM:BEGIN -->`).
//!
//! 둘 다 idempotent — 반복 실행해도 안전. 자연어 대화로 LLM 이 호출 가능.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{anyhow, bail, Context, Result};
use serde_json::{json, Value};

use openxgram_core::paths::{db_path, manifest_path};
use openxgram_db::{Db, DbConfig};
use openxgram_manifest::InstallManifest;

const CLAUDE_MD_BEGIN: &str = "<!-- OPENXGRAM:BEGIN — auto-generated by `xgram identity inject` (수정 시 marker 사이만) -->";
const CLAUDE_MD_END: &str = "<!-- OPENXGRAM:END -->";

/// MCP 등록 scope.
pub enum McpScope {
    /// `~/.claude.json` — 모든 프로젝트에서 사용 가능.
    User,
    /// `./.mcp.json` — 이 프로젝트만.
    Project,
    /// 사용자가 지정한 경로.
    Custom(PathBuf),
}

/// `xgram mcp install` 본체.
///
/// `include_password` 가 true 면 현재 XGRAM_KEYSTORE_PASSWORD env 를 config 에
/// 평문 저장 (편리). false 면 env 만 reference — 사용자가 별도 설정 필요.
pub fn run_install(scope: McpScope, data_dir: &Path, include_password: bool) -> Result<()> {
    let config_path = resolve_config_path(scope)?;
    let xgram_bin = std::env::current_exe()
        .context("현재 xgram 바이너리 경로 추출 실패")?;

    // 기존 config 읽기 (없으면 빈 객체).
    let mut config: Value = if config_path.exists() {
        let raw = fs::read_to_string(&config_path)
            .with_context(|| format!("{} 읽기 실패", config_path.display()))?;
        serde_json::from_str(&raw)
            .with_context(|| format!("{} JSON 파싱 실패", config_path.display()))?
    } else {
        if let Some(parent) = config_path.parent() {
            fs::create_dir_all(parent).context("config 디렉토리 생성")?;
        }
        json!({})
    };

    // mcpServers.openxgram 항목 작성.
    let mut server_entry = json!({
        "command": xgram_bin.display().to_string(),
        "args": ["mcp-serve", "--data-dir", data_dir.display().to_string()],
    });
    if include_password {
        if let Ok(pw) = std::env::var("XGRAM_KEYSTORE_PASSWORD") {
            server_entry["env"] = json!({ "XGRAM_KEYSTORE_PASSWORD": pw });
        }
    }

    let servers = config
        .as_object_mut()
        .ok_or_else(|| anyhow!("{} 의 root 가 JSON object 아님", config_path.display()))?
        .entry("mcpServers".to_string())
        .or_insert_with(|| json!({}));
    let servers_map = servers
        .as_object_mut()
        .ok_or_else(|| anyhow!("mcpServers 가 object 아님"))?;
    servers_map.insert("openxgram".to_string(), server_entry);

    // 쓰기 (pretty).
    let new_content = serde_json::to_string_pretty(&config)?;
    fs::write(&config_path, new_content)
        .with_context(|| format!("{} 쓰기 실패", config_path.display()))?;

    println!("✓ MCP 등록 완료: {}", config_path.display());
    println!("  xgram binary : {}", xgram_bin.display());
    println!("  data_dir     : {}", data_dir.display());
    println!(
        "  패스워드     : {}",
        if include_password {
            "config 에 포함 (XGRAM_KEYSTORE_PASSWORD env)"
        } else {
            "포함 안 함 (사용자가 별도 export 필요)"
        }
    );
    println!();

    // 글로벌 설정 (~/.claude/CLAUDE.md + env vars) 에서 webhook/token 자동 import.
    println!("→ 글로벌 설정에서 webhook / token 자동 import 시도");
    match import_global_defaults(data_dir) {
        Ok(0) => println!("  (가져올 글로벌 설정 없음 — 스킵)"),
        Ok(n) => println!("  ✓ {n}개 자동 등록"),
        Err(e) => eprintln!("  ⚠ global import 실패 (계속): {e}"),
    }
    println!();
    println!("Claude Code (또는 다른 MCP 클라이언트) 재시작 후 `openxgram.*` 도구 사용 가능.");
    Ok(())
}

/// `xgram identity inject` 본체.
///
/// `target` 파일에 OpenXgram identity context 블록을 marker 기반으로 주입/갱신.
/// 파일 없으면 생성. 마커 이외 영역은 절대 건드리지 않음.
pub fn run_inject(target: &Path, data_dir: &Path) -> Result<()> {
    let block = generate_context_block(data_dir)?;

    let existing = if target.exists() {
        fs::read_to_string(target)
            .with_context(|| format!("{} 읽기 실패", target.display()))?
    } else {
        String::new()
    };

    let new_content = if let (Some(start_idx), Some(end_idx)) = (
        existing.find(CLAUDE_MD_BEGIN),
        existing.find(CLAUDE_MD_END),
    ) {
        // 기존 블록 교체 — marker 사이만.
        let end_idx_full = end_idx + CLAUDE_MD_END.len();
        let mut out = String::with_capacity(existing.len());
        out.push_str(&existing[..start_idx]);
        out.push_str(&block);
        out.push_str(&existing[end_idx_full..]);
        out
    } else {
        // 새로 추가 — 파일 끝에.
        let mut out = existing;
        if !out.is_empty() && !out.ends_with('\n') {
            out.push('\n');
        }
        if !out.is_empty() {
            out.push('\n');
        }
        out.push_str(&block);
        out.push('\n');
        out
    };

    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent).ok();
    }
    fs::write(target, new_content)
        .with_context(|| format!("{} 쓰기 실패", target.display()))?;

    println!("✓ identity context 주입 완료: {}", target.display());
    println!("  marker: {} … {}", CLAUDE_MD_BEGIN, CLAUDE_MD_END);
    Ok(())
}

fn resolve_config_path(scope: McpScope) -> Result<PathBuf> {
    match scope {
        McpScope::User => {
            let home = std::env::var("HOME")
                .or_else(|_| std::env::var("USERPROFILE"))
                .map_err(|_| anyhow!("HOME / USERPROFILE 둘 다 미설정"))?;
            Ok(PathBuf::from(home).join(".claude.json"))
        }
        McpScope::Project => Ok(std::env::current_dir()?.join(".mcp.json")),
        McpScope::Custom(p) => Ok(p),
    }
}

fn generate_context_block(data_dir: &Path) -> Result<String> {
    let mp = manifest_path(data_dir);
    let manifest = InstallManifest::read(&mp)
        .with_context(|| format!("manifest 미발견: {}. xgram init 먼저", mp.display()))?;
    let master = manifest
        .registered_keys
        .iter()
        .find(|k| k.alias == "master")
        .ok_or_else(|| anyhow!("manifest 에 master key 없음"))?;

    let peer_count = peer_count_quiet(data_dir);

    let mut s = String::new();
    s.push_str(CLAUDE_MD_BEGIN);
    s.push_str("\n\n## OpenXgram Identity (이 프로젝트)\n\n");
    s.push_str(&format!("- **alias**: `{}`\n", manifest.machine.alias));
    s.push_str(&format!("- **address**: `{}`\n", master.address));
    s.push_str(&format!("- **data_dir**: `{}`\n", data_dir.display()));
    s.push_str(&format!("- **linked peers**: {} (자세히 `openxgram.list_peers`)\n", peer_count));
    s.push_str("\n### 사용 가능한 MCP 도구 (`openxgram.*`)\n\n");
    s.push_str("- `whoami` — 이 프로젝트의 신원 확인\n");
    s.push_str("- `list_peers` — 메시지 보낼 수 있는 상대\n");
    s.push_str("- `peer_send(alias, body)` — 다른 에이전트한테 메시지\n");
    s.push_str("- `recv_messages(limit?, since_rfc3339?, sender?)` — 내 inbox (시간 내림차순)\n");
    s.push_str("- `recall_messages(query, k?)` — 과거 메시지 벡터 검색 (sqlite-vec KNN)\n");
    s.push_str("- `list_sessions` — 세션 목록\n");
    s.push_str("- `list_memories_by_kind(kind)` — L2 facts/decisions/references/rules\n");
    s.push_str("- `vault_*` — 자격증명 (XGRAM_KEYSTORE_PASSWORD env 필요)\n");
    s.push_str("\n### 사용 패턴\n\n");
    s.push_str("- 세션 시작 시 `recv_messages` 한 번 호출해 받은 메시지 확인 권장\n");
    s.push_str("- 다른 에이전트 호출 시 먼저 `list_peers` 로 사용 가능한 alias 확인\n");
    s.push_str("- 과거 대화 회상 시 `recall_messages` (벡터 검색)\n\n");
    s.push_str(CLAUDE_MD_END);
    Ok(s)
}

fn peer_count_quiet(data_dir: &Path) -> usize {
    use openxgram_peer::PeerStore;
    let path = db_path(data_dir);
    if !path.exists() {
        return 0;
    }
    let Ok(mut db) = Db::open(DbConfig {
        path,
        ..Default::default()
    }) else {
        return 0;
    };
    PeerStore::new(&mut db).list().map(|v| v.len()).unwrap_or(0)
}

/// 글로벌 ~/.claude/CLAUDE.md + env vars 에서 token / webhook 을 추출해
/// 프로젝트 vault 에 등록. install 시 자동 호출 — 사용자가 매 프로젝트마다
/// 다시 입력 안 함. 이미 vault 에 있으면 skip (overwrite 안 함).
///
/// vault 키 컨벤션:
///   - `notify.discord.webhook_url`
///   - `notify.discord.bot_token`
///   - `notify.discord.channel_id`
///   - `notify.telegram.bot_token`
///   - `notify.telegram.chat_id`
///   - `agent.anthropic.api_key`
pub fn import_global_defaults(data_dir: &Path) -> Result<usize> {
    use openxgram_vault::VaultStore;
    let pw = match std::env::var("XGRAM_KEYSTORE_PASSWORD") {
        Ok(p) => p,
        Err(_) => {
            eprintln!("(global import skip — XGRAM_KEYSTORE_PASSWORD env 없음)");
            return Ok(0);
        }
    };

    // 1. 글로벌 CLAUDE.md 들에서 추출. 검색 순서 (뒤가 우선 — 더 구체적):
    //    a. ~/.claude/CLAUDE.md  (Claude Code private global)
    //    b. ~/CLAUDE.md          (사용자 home 의 project-rooted global)
    //    c. ./CLAUDE.md          (현재 프로젝트)
    let mut found: Vec<(&'static str, String)> = Vec::new();
    let mut md_candidates: Vec<PathBuf> = Vec::new();
    if let Ok(home) = std::env::var("HOME").or_else(|_| std::env::var("USERPROFILE")) {
        md_candidates.push(PathBuf::from(&home).join(".claude/CLAUDE.md"));
        md_candidates.push(PathBuf::from(&home).join("CLAUDE.md"));
    }
    if let Ok(cwd) = std::env::current_dir() {
        md_candidates.push(cwd.join("CLAUDE.md"));
    }
    for md in &md_candidates {
        if !md.exists() {
            continue;
        }
        let Ok(content) = fs::read_to_string(md) else { continue };
        for (md_key, vault_key) in &[
            ("DISCORD_WEBHOOK_URL", "notify.discord.webhook_url"),
            ("DISCORD_BOT_TOKEN", "notify.discord.bot_token"),
            ("DISCORD_CHANNEL_ID", "notify.discord.channel_id"),
            ("TELEGRAM_BOT_TOKEN", "notify.telegram.bot_token"),
            ("TELEGRAM_CHAT_ID", "notify.telegram.chat_id"),
            ("ANTHROPIC_API_KEY", "agent.anthropic.api_key"),
        ] {
            if let Some(v) = extract_quoted(&content, md_key) {
                found.retain(|(k, _)| k != vault_key);
                found.push((vault_key, v));
            }
        }
    }

    // 2. env vars (CLAUDE.md 못 찾았어도 우선 적용).
    for (env_key, vault_key) in &[
        ("DISCORD_WEBHOOK_URL", "notify.discord.webhook_url"),
        ("DISCORD_BOT_TOKEN", "notify.discord.bot_token"),
        ("DISCORD_CHANNEL_ID", "notify.discord.channel_id"),
        ("TELEGRAM_BOT_TOKEN", "notify.telegram.bot_token"),
        ("TELEGRAM_CHAT_ID", "notify.telegram.chat_id"),
        ("ANTHROPIC_API_KEY", "agent.anthropic.api_key"),
    ] {
        if let Ok(v) = std::env::var(env_key) {
            // CLAUDE.md 에서 같은 키 추출됐으면 env 가 덮어씀 (현재 셸 우선).
            found.retain(|(k, _)| k != vault_key);
            found.push((vault_key, v));
        }
    }

    if found.is_empty() {
        return Ok(0);
    }

    // 3. vault 등록 (기존 키는 skip — overwrite 안 함, 부주의 방지).
    let mut db = Db::open(DbConfig {
        path: db_path(data_dir),
        ..Default::default()
    })?;
    db.migrate()?;
    let existing: std::collections::HashSet<String> = VaultStore::new(&mut db)
        .list()
        .map(|entries| entries.into_iter().map(|e| e.key).collect())
        .unwrap_or_default();

    let mut count = 0;
    for (key, value) in &found {
        if existing.contains(*key) {
            eprintln!("  - skip {}: 이미 vault 에 있음", key);
            continue;
        }
        VaultStore::new(&mut db)
            .set(key, value.as_bytes(), &pw, &[])
            .with_context(|| format!("vault set {key} 실패"))?;
        eprintln!("  + {}: 글로벌에서 자동 등록", key);
        count += 1;
    }
    Ok(count)
}

/// CLAUDE.md 같은 곳에서 `KEY="value"` 또는 `KEY='value'` 패턴 추출.
fn extract_quoted(text: &str, key: &str) -> Option<String> {
    for line in text.lines() {
        let trimmed = line.trim();
        if !trimmed.starts_with(key) {
            continue;
        }
        let after = trimmed.trim_start_matches(key).trim_start();
        if !after.starts_with('=') {
            continue;
        }
        let val_part = after[1..].trim();
        // "..." 또는 '...' 추출
        if let Some(s) = val_part.strip_prefix('"').and_then(|s| s.strip_suffix('"')) {
            return Some(s.to_string());
        }
        if let Some(s) = val_part.strip_prefix('\'').and_then(|s| s.strip_suffix('\'')) {
            return Some(s.to_string());
        }
    }
    None
}

/// CLAUDE.md 의 OpenXgram 블록 제거 (uninstall 시).
pub fn run_uninject(target: &Path) -> Result<()> {
    if !target.exists() {
        bail!("{} 없음", target.display());
    }
    let content = fs::read_to_string(target)?;
    let (Some(start_idx), Some(end_idx)) = (
        content.find(CLAUDE_MD_BEGIN),
        content.find(CLAUDE_MD_END),
    ) else {
        bail!("OpenXgram marker 없음 — 이미 제거됐거나 다른 파일");
    };
    let end_idx_full = end_idx + CLAUDE_MD_END.len();
    let mut out = String::with_capacity(content.len());
    out.push_str(&content[..start_idx]);
    out.push_str(&content[end_idx_full..]);
    // 연속 빈줄 정리.
    let trimmed = out.trim_end_matches('\n').to_string() + "\n";
    fs::write(target, trimmed)?;
    println!("✓ OpenXgram 블록 제거: {}", target.display());
    Ok(())
}
